/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dAmihl' at '25.03.16 16:49' with Gradle 2.9
 *
 * @author dAmihl, @date 25.03.16 16:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
